package constants

var (
	TEAM_EXISTS  = "TEAM_EXISTS"
	PR_EXISTS    = "PR_EXISTS"
	NOT_ASSIGNED = "NOT_ASSIGNED"
	NO_CANDIDATE = "NO_CANDIDATE"
	PR_MERGED    = "PR_MERGED"
	NOT_FOUND    = "NOT_FOUND"
)
